### ISSUE TITLE
Error Parsing Missing Achievements

### ISSUE THREAD

**Issue by davidgrieser** [teoucsb82/rbghub#2]
Tried to use the following team and encountered an error.

```
Bronnys-Dethecus, Dize-Dethecus, Buðspencer-Dethecus, Mup-Dethecus, Namî-Dethecus, Eichhörn-Dethecus, Trollmage-Dethecus, Ðood-Dethecus, Mortalas-Dethecus, Adex-Dethecus
```

```
Showing /Users/david/work/lenda/code/interviews/teo/rbghub/app/views/teamstats/show.html.erb where line #29 raised:

undefined method `[]' for nil:NilClass
Extracted source (around line #29):
26          <% @teamstat.toon_db.each do |armory| %>
27              <% unless armory["status"] == "nok" %>
28                  <!-- Set Achievements -->
29                  <% achievements = armory["achievements"]["achievementsCompleted"] %>
30                  <% title = "" %>
31                  <% title = "Challenger" if achievements.include? 2090 %>
32                  <% title = "Rival" if achievements.include? 2093 %>
```

**Comment by teoucsb82** [comment]
Hi David,

Ack, sorry about that, I'll have to take a look at what's breaking later
this evening. It could be one of many things (I know Blizzard changed their
API -- and I didn't have it abstracted, obviously -- plus there could be
new game mechanics I'm not accounting for since I stopped playing in the
Mists of Pandaria expansion).

It worked with my sample characters (I'm bad, I have a level 90 of each
class on Blackrock-US, with names formatted like "teomage," "teoshaman,"
"teowarlock", etc.), but as soon as I get off work I'll take a closer look
at the error/try some live accounts and get this thing operational for you!

Best,
Teo

On Wed, Mar 4, 2015 at 9:46 AM, David Grieser notifications@github.com
wrote:

> Tried to use the following team and encountered an error.
> 
> Bronnys-Dethecus, Dize-Dethecus, Buðspencer-Dethecus, Mup-Dethecus, Namî-Dethecus, Eichhörn-Dethecus, Trollmage-Dethecus, Ðood-Dethecus, Mortalas-Dethecus, Adex-Dethecus
> 
> Showing /Users/david/work/lenda/code/interviews/teo/rbghub/app/views/teamstats/show.html.erb where line #29 raised:
> 
> undefined method `[]' for nil:NilClass
> Extracted source (around line #29):
> 26          <% @teamstat.toon_db.each do |armory| %>
> 27              <% unless armory["status"] == "nok" %>
> 28                  
> 29                  <% achievements = armory["achievements"]["achievementsCompleted"] %>
> 30                  <% title = "" %>
> 31                  <% title = "Challenger" if achievements.include? 2090 %>
> 32                  <% title = "Rival" if achievements.include? 2093 %>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teoucsb82/rbghub/issues/2.

## 

http://www.dellamico.com

**Comment by teoucsb82** [comment]
Hi David,

That wouldn't be a European server you're trying to check, would it? I was having the wildest time with this until I actually went and tried to do a manual lookup through the real armory and realized that these toons only exist in EU. If that is indeed the case, you'll need to toggle the dropdown underneath the main text area input on the first page to "EU" and rerun, fingers crossed it works for you. No promises on how accurate the data is (and also the code could be refactored about 100 times over now that I look at it again 12+ months after originally writing it), but hopefully that fixes it!

**Comment by davidgrieser** [comment]
Haha, could have been. I thought I was getting US toons.

**Comment by davidgrieser** [comment]
That was it. Might want to add in some error handling, but considering the lack of use, probably isn't needed.
